### ISSUE TITLE
default length in add_observations_paper.py is too small

### ISSUE THREAD

**Issue by SaulAryehKohn** [HERA-Team/RTP#1]
The calculated length for finding neighbours for PAPER 128 data is too small. There's a command line argument that overrides it: `--length=10` (i.e. a 10min observation) successfully matches files to their neighbours.

If you are like me and forget extra command line arguments from time to time, here is the SQL to get rid of bad `hera_rtp.neighbours` matches for that day, and then get rid of the entries in the `hera_rtp.observation` table so you can try again with your chosen length (example for JD=2456617):

```
DELETE FROM neighbors WHERE neighbors.high_neighbor_id IN (SELECT obsnum FROM observation WHERE observation.date LIKE '2456617%');

DELETE FROM observation WHERE observation.date LIKE '2456617%';
```

**Comment by pkgw** [comment]
Superseded.
