### ISSUE TITLE
Autocorrelation plots are illegible.

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/RTP#3]
The current HERA pipeline has a PLOTAUTOS step but the plots that it produces are basically illegible. If you have a SSH port forward to the UPenn Librarian running on port 51110, [this link shows an example](http://localhost:51110/stream/zen.2457555.50795.xx.uvc.autos.png).

Hopefully it won't take much work to tidy them up; the relevant `plot_uv` call is in [do_PLOTAUTOS.sh](https://github.com/HERA-Team/RTP/blob/master/scripts/hera/do_PLOTAUTOS.sh).

**Comment by SaulAryehKohn** [comment]
This is probably easily fixed with a quick modification to `plot_uv` to turn-off axis titles. You could just put that custom version in the RTP scripts directory.

**Comment by dannyjacobs** [comment]
A better option would be to put the titles inside the plot window with a call to text() and to only turn off the axis labels for the non-edge plots. The code to do this is in capo/dcj/scripts/plot_uv_mpi.py

**Comment by carinacheng** [comment]
Okay, I made some simple edits to plot_uv.py in the RTP scripts directory. I added a '--pretty' option to make tick marks and labels smaller, and also only put the labels on the outermost axes. Here is what some of the autos look like for the HH array and all antennas. I added the --pretty option to PLOTAUTOS and committed both edits.

![screen shot 2016-06-16 at 5 45 08 pm](https://cloud.githubusercontent.com/assets/7808996/16137650/55d6caee-33ea-11e6-8f90-273b5807520b.png)
![screen shot 2016-06-16 at 5 45 21 pm](https://cloud.githubusercontent.com/assets/7808996/16137654/5ac8f07c-33ea-11e6-8214-53035a5301b1.png)

**Comment by pkgw** [comment]
These plots definitely look better. Did you push your commits? I don't see any new ones in this repository. Has this been deployed on `qmaster` and the still nodes?

In the #herasoftware slack channel Danny also suggested putting titles inside the plots so that you can set vspace=0.

**Comment by pkgw** [comment]
It took a long time but the improved plots are now deployed on site.
